"""Validation helpers for untrusted upload names and storage paths."""

from __future__ import annotations

from pathlib import PurePath, PureWindowsPath
from uuid import uuid4


MAX_UPLOAD_FILENAME_LENGTH = 255


def prepare_upload_filename(raw_filename: str | None) -> tuple[str, str]:
    """Return ``(display_name, generated_storage_name)`` for an upload.

    The display name is retained for provenance, but the filesystem name is
    always generated by the server. Separators, traversal components, control
    characters, absolute Windows/POSIX paths, and NUL bytes are rejected.
    """
    if not isinstance(raw_filename, str):
        raise ValueError("filename_required")
    display_name = raw_filename.strip()
    if not display_name:
        raise ValueError("filename_required")
    if len(display_name) > MAX_UPLOAD_FILENAME_LENGTH:
        raise ValueError("filename_too_long")
    if "\x00" in display_name or "/" in display_name or "\\" in display_name:
        raise ValueError("filename_path_separator")
    if any(ord(char) < 32 or ord(char) == 127 for char in display_name):
        raise ValueError("filename_control_character")
    if PurePath(display_name).is_absolute() or PureWindowsPath(display_name).is_absolute() or PureWindowsPath(display_name).drive:
        raise ValueError("filename_absolute_path")
    if any(part in {".", ".."} for part in PurePath(display_name).parts):
        raise ValueError("filename_traversal")

    suffix = PurePath(display_name).suffix.lower()
    storage_name = f"upload-{uuid4().hex}{suffix}"
    return display_name, storage_name
