"""Strict contracts for the controlled clinical-case record module.

This surface stores human-authored records, reviews, and feedback only.  It
does not expose a diagnosis, prescription, recommendation, or generated
clinical conclusion contract.
"""

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict, Field, field_validator, model_validator

from rick_contracts.base import StrictContractModel


CASE_CONTRACT_VERSION = "clinical-case-contract-v1"
CASE_SCOPE_STATUS = "record_review_feedback_only"

CaseStatus = Literal["open", "reviewed"]
ReviewDecision = Literal["recorded", "needs_revision", "declined"]
FeedbackKind = Literal["correction", "clarification", "quality_issue", "scope_note"]
HypothesisStatus = Literal["open", "supported", "refuted", "deferred"]
EvidenceSourceType = Literal["document", "chunk", "conversation", "external_reference", "manual"]
AgentModelStatus = Literal["authorized", "revoked"]


def _required_text(value: str, *, field_name: str) -> str:
    candidate = value.strip()
    if not candidate:
        raise ValueError(f"{field_name} must not be blank")
    return candidate


class CaseCreateRequest(StrictContractModel):
    """A human-authored record; scope is always server-derived.

    ``record`` remains accepted for clients of the first local draft.  New
    clients should use ``summary`` plus the structured references below.
    """

    title: str = Field(min_length=1, max_length=160)
    summary: str | None = Field(default=None, min_length=1, max_length=20_000)
    record: str | None = Field(default=None, min_length=1, max_length=20_000)
    hypotheses: list["CaseHypothesisInput"] = Field(default_factory=list, max_length=32)
    evidence: list["CaseEvidenceInput"] = Field(default_factory=list, max_length=64)
    tags: list[str] = Field(default_factory=list, max_length=16)

    @field_validator("title", "summary", "record")
    @classmethod
    def normalize_optional_text(cls, value: str | None, info):
        if value is None:
            return None
        return _required_text(value, field_name=info.field_name)

    @field_validator("tags")
    @classmethod
    def normalize_tags(cls, value: list[str]) -> list[str]:
        result: list[str] = []
        for item in value:
            candidate = item.strip()
            if not candidate:
                raise ValueError("tags must not contain blank values")
            if len(candidate) > 64:
                raise ValueError("tags must contain at most 64 characters")
            if candidate not in result:
                result.append(candidate)
        return result

    @model_validator(mode="after")
    def require_summary_or_record(self):
        if self.summary is None and self.record is None:
            raise ValueError("summary or record is required")
        return self


class CaseUpdateRequest(StrictContractModel):
    """Editable human record fields.  Status changes happen through review."""

    title: str | None = Field(default=None, min_length=1, max_length=160)
    summary: str | None = Field(default=None, min_length=1, max_length=20_000)
    record: str | None = Field(default=None, min_length=1, max_length=20_000)
    hypotheses: list["CaseHypothesisInput"] | None = Field(default=None, max_length=32)
    evidence: list["CaseEvidenceInput"] | None = Field(default=None, max_length=64)
    tags: list[str] | None = Field(default=None, max_length=16)

    @field_validator("title", "summary", "record")
    @classmethod
    def normalize_optional_text(cls, value: str | None, info):
        if value is None:
            return None
        return _required_text(value, field_name=info.field_name)

    @field_validator("tags")
    @classmethod
    def normalize_optional_tags(cls, value: list[str] | None) -> list[str] | None:
        if value is None:
            return None
        return CaseCreateRequest.normalize_tags(value)

    @model_validator(mode="after")
    def require_change(self):
        if all(value is None for value in (self.title, self.summary, self.record, self.hypotheses, self.evidence, self.tags)):
            raise ValueError("at least one case field is required")
        return self


class CaseHypothesisInput(StrictContractModel):
    """Human-entered hypothesis metadata; never generated by this module."""

    hypothesis_id: str | None = Field(default=None, min_length=1, max_length=128)
    statement: str = Field(min_length=1, max_length=4_000)
    status: HypothesisStatus = "open"

    @field_validator("hypothesis_id", "statement")
    @classmethod
    def normalize_text(cls, value: str | None, info):
        if value is None:
            return None
        return _required_text(value, field_name=info.field_name)


class CaseHypothesis(StrictContractModel):
    hypothesis_id: str = Field(min_length=1, max_length=128)
    statement: str = Field(min_length=1, max_length=4_000)
    status: HypothesisStatus = "open"


class CaseEvidenceInput(StrictContractModel):
    """Human-entered evidence reference; content is never fetched here."""

    evidence_id: str | None = Field(default=None, min_length=1, max_length=128)
    source_type: EvidenceSourceType
    source_id: str = Field(min_length=1, max_length=256)
    locator: str | None = Field(default=None, max_length=256)
    label: str | None = Field(default=None, max_length=256)

    @field_validator("evidence_id", "source_id", "locator", "label")
    @classmethod
    def normalize_text(cls, value: str | None, info):
        if value is None:
            return None
        return _required_text(value, field_name=info.field_name)


class CaseEvidence(StrictContractModel):
    evidence_id: str = Field(min_length=1, max_length=128)
    source_type: EvidenceSourceType
    source_id: str = Field(min_length=1, max_length=256)
    locator: str | None = Field(default=None, max_length=256)
    label: str | None = Field(default=None, max_length=256)


class AuthorizedAgentModel(StrictContractModel):
    """Deployment-owned catalog entry; this module does not invoke it."""

    model_config = ConfigDict(extra="forbid", strict=True, protected_namespaces=())

    agent_id: str = Field(min_length=1, max_length=128)
    model_id: str = Field(min_length=1, max_length=256)
    catalog_version: str = Field(min_length=1, max_length=64)
    status: AgentModelStatus = "authorized"
    purpose: Literal["metadata_only", "human_review_assist"] = "metadata_only"


class AgentModelCatalogResponse(StrictContractModel):
    catalog_status: Literal["not_configured", "configured"]
    items: list[AuthorizedAgentModel] = Field(default_factory=list, max_length=100)


class CaseReviewRequest(StrictContractModel):
    decision: ReviewDecision
    review_note: str = Field(min_length=1, max_length=8_000)

    @field_validator("review_note")
    @classmethod
    def normalize_note(cls, value: str) -> str:
        return _required_text(value, field_name="review_note")


class CaseFeedbackRequest(StrictContractModel):
    kind: FeedbackKind
    feedback_note: str = Field(min_length=1, max_length=8_000)

    @field_validator("feedback_note")
    @classmethod
    def normalize_note(cls, value: str) -> str:
        return _required_text(value, field_name="feedback_note")


class CaseRecord(StrictContractModel):
    contract_version: Literal[CASE_CONTRACT_VERSION] = CASE_CONTRACT_VERSION
    clinical_scope_status: Literal[CASE_SCOPE_STATUS] = CASE_SCOPE_STATUS
    case_id: str = Field(min_length=1, max_length=128)
    tenant_id: str = Field(min_length=1, max_length=128)
    workspace_id: str = Field(min_length=1, max_length=128)
    owner_user_id: str = Field(min_length=1, max_length=128)
    title: str = Field(min_length=1, max_length=160)
    summary: str = Field(min_length=1, max_length=20_000)
    record: str = Field(min_length=1, max_length=20_000)
    hypotheses: list[CaseHypothesis] = Field(default_factory=list, max_length=32)
    evidence: list[CaseEvidence] = Field(default_factory=list, max_length=64)
    agent_model: AuthorizedAgentModel | None = None
    tags: list[str] = Field(default_factory=list, max_length=16)
    status: CaseStatus = "open"
    created_by_user_id: str = Field(min_length=1, max_length=128)
    created_at: float = Field(ge=0)
    updated_by_user_id: str = Field(min_length=1, max_length=128)
    updated_at: float = Field(ge=0)
    last_request_id: str | None = Field(default=None, max_length=128)
    review_count: int = Field(default=0, ge=0)
    feedback_count: int = Field(default=0, ge=0)
    last_review_at: float | None = Field(default=None, ge=0)
    last_feedback_at: float | None = Field(default=None, ge=0)


class CaseReview(StrictContractModel):
    contract_version: Literal[CASE_CONTRACT_VERSION] = CASE_CONTRACT_VERSION
    review_id: str = Field(min_length=1, max_length=128)
    case_id: str = Field(min_length=1, max_length=128)
    tenant_id: str = Field(min_length=1, max_length=128)
    workspace_id: str = Field(min_length=1, max_length=128)
    decision: ReviewDecision
    review_note: str = Field(min_length=1, max_length=8_000)
    reviewer_user_id: str = Field(min_length=1, max_length=128)
    created_at: float = Field(ge=0)
    request_id: str | None = Field(default=None, max_length=128)


class CaseFeedback(StrictContractModel):
    contract_version: Literal[CASE_CONTRACT_VERSION] = CASE_CONTRACT_VERSION
    feedback_id: str = Field(min_length=1, max_length=128)
    case_id: str = Field(min_length=1, max_length=128)
    tenant_id: str = Field(min_length=1, max_length=128)
    workspace_id: str = Field(min_length=1, max_length=128)
    kind: FeedbackKind
    feedback_note: str = Field(min_length=1, max_length=8_000)
    feedback_user_id: str = Field(min_length=1, max_length=128)
    created_at: float = Field(ge=0)
    request_id: str | None = Field(default=None, max_length=128)


class CaseListResponse(StrictContractModel):
    items: list[CaseRecord] = Field(default_factory=list, max_length=100)
    total: int = Field(ge=0)
    next_offset: int | None = Field(default=None, ge=0)


class CaseDetailResponse(StrictContractModel):
    case: CaseRecord
    reviews: list[CaseReview] = Field(default_factory=list, max_length=100)
    feedback: list[CaseFeedback] = Field(default_factory=list, max_length=100)


# These request models refer to the structured input types declared below them.
CaseCreateRequest.model_rebuild()
CaseUpdateRequest.model_rebuild()


__all__ = [
    "CASE_CONTRACT_VERSION",
    "CASE_SCOPE_STATUS",
    "CaseCreateRequest",
    "CaseUpdateRequest",
    "CaseHypothesisInput",
    "CaseHypothesis",
    "CaseEvidenceInput",
    "CaseEvidence",
    "AuthorizedAgentModel",
    "AgentModelCatalogResponse",
    "CaseReviewRequest",
    "CaseFeedbackRequest",
    "CaseRecord",
    "CaseReview",
    "CaseFeedback",
    "CaseListResponse",
    "CaseDetailResponse",
    "CaseStatus",
    "ReviewDecision",
    "FeedbackKind",
    "HypothesisStatus",
    "EvidenceSourceType",
    "AgentModelStatus",
]
