"""Canonical ingestion package — validated pipeline as platform capability."""

from rick_ingestion.chunking import (
    CHUNKER_VERSION,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_OVERLAP,
    ChunkPlan,
    ChunkingStrategy,
    RecursiveChunkingStrategy,
)
from rick_ingestion.jobs import (
    DEFAULT_MAX_JOBS,
    MAX_HEARTBEATS,
    PERMANENT_ERROR_CODES,
    TERMINAL_STATES,
    TRANSIENT_ERROR_CODES,
    IngestionJob,
    InvalidTransitionError,
    is_retryable,
)
from rick_ingestion.parsers import (
    DEFAULT_PARSER_LIMITS,
    DEFAULT_PARSER_TIMEOUT_SECONDS,
    MAX_ARCHIVE_COMPRESSION_RATIO,
    MAX_ARCHIVE_MEMBER_BYTES,
    MAX_ARCHIVE_MEMBERS,
    MAX_ARCHIVE_UNCOMPRESSED_BYTES,
    MAX_FILE_BYTES,
    MAX_PARSER_TIMEOUT_SECONDS,
    DEFAULT_PARSER_MEMORY_BYTES,
    MAX_PARSER_MEMORY_BYTES,
    MAX_PARSED_PAGES,
    MAX_PARSED_SECTIONS,
    MAX_PARSED_TEXT_CHARS,
    PARSER_VERSION,
    ArchiveInspection,
    ArchiveLimitError,
    ControlledPdfParser,
    DocxParser,
    DocumentParser,
    FileInspection,
    FilenameValidationError,
    InProcessParserRunner,
    ProcessParserRunner,
    MarkdownParser,
    MimeMismatchError,
    ParseError,
    ParsedDocument,
    ParsedPage,
    ParserLimits,
    ParserRunner,
    ParserTimeoutError,
    TxtParser,
    UnsupportedFormatError,
    execute_parser,
    generated_storage_name,
    inspect_file,
    normalize_filename,
    parser_for,
    sanitize_display_filename,
    validate_archive,
    validate_filename,
    validate_file,
)
from rick_ingestion.pipeline import EmbeddingProvider, IngestionService, VectorStore
from rick_ingestion.admission import (
    ALLOWED_OPERATIONS,
    ALLOWED_SOURCE_TYPES,
    InvalidChecksumError,
    InvalidUploadFieldError,
    InvalidUploadSizeError,
    MAX_TOKEN_LENGTH,
    MAX_UPLOAD_BYTES,
    ObjectScopeLike,
    UnsupportedOperationError,
    UnsupportedSourceTypeError,
    UploadJobEnvelope,
    UploadJobEnvelopeError,
    UploadJobScope,
)

__all__ = [
    "CHUNKER_VERSION", "DEFAULT_CHUNK_SIZE", "DEFAULT_OVERLAP",
    "DEFAULT_MAX_JOBS", "DEFAULT_PARSER_LIMITS", "DEFAULT_PARSER_TIMEOUT_SECONDS",
    "MAX_ARCHIVE_COMPRESSION_RATIO", "MAX_ARCHIVE_MEMBER_BYTES", "MAX_ARCHIVE_MEMBERS",
    "MAX_ARCHIVE_UNCOMPRESSED_BYTES", "MAX_FILE_BYTES", "MAX_HEARTBEATS",
    "MAX_PARSER_TIMEOUT_SECONDS", "DEFAULT_PARSER_MEMORY_BYTES", "MAX_PARSER_MEMORY_BYTES",
    "MAX_PARSED_PAGES", "MAX_PARSED_SECTIONS",
    "MAX_PARSED_TEXT_CHARS", "PARSER_VERSION", "PERMANENT_ERROR_CODES",
    "TERMINAL_STATES", "TRANSIENT_ERROR_CODES",
    "ArchiveInspection", "ArchiveLimitError", "ChunkPlan", "ChunkingStrategy",
    "ControlledPdfParser", "DocxParser", "DocumentParser", "EmbeddingProvider",
    "FileInspection", "FilenameValidationError", "InProcessParserRunner", "ProcessParserRunner", "IngestionJob",
    "IngestionService", "InvalidTransitionError", "MarkdownParser", "MimeMismatchError",
    "ParseError", "ParsedDocument", "ParsedPage", "ParserLimits", "ParserRunner",
    "ParserTimeoutError", "TxtParser", "UnsupportedFormatError", "VectorStore",
    "execute_parser", "generated_storage_name", "inspect_file", "is_retryable",
    "normalize_filename", "parser_for", "sanitize_display_filename", "validate_archive",
    "validate_filename", "validate_file",
    "ALLOWED_OPERATIONS", "ALLOWED_SOURCE_TYPES", "InvalidChecksumError",
    "InvalidUploadFieldError", "InvalidUploadSizeError", "MAX_TOKEN_LENGTH",
    "MAX_UPLOAD_BYTES", "ObjectScopeLike", "UnsupportedOperationError",
    "UnsupportedSourceTypeError", "UploadJobEnvelope", "UploadJobEnvelopeError",
    "UploadJobScope",
]
