#!/usr/bin/env python3
"""Create a new immutable control bundle from an explicit audit inventory."""
from __future__ import annotations

import argparse
import hashlib
import io
import json
from pathlib import Path
import tarfile


def allowed(path: str) -> bool:
    p = Path(path)
    return (not p.is_absolute() and '..' not in p.parts and
            any(path.startswith(prefix) for prefix in (
                '.agent/legacy-v1/', '.review-control-history/', '.gauntlet-state-of-art/',
                'docs/reports/evidence/', 'artifacts/rec-m0-v3/', 'artifacts/rec-m0-v4/')) or
            path in {
                'docs/progress/release-evidence.json',
                '.runtime/phase-3/capability-matrix.json',
                '.runtime/phase-3/frontend-supply-runtime-evidence.json',
                '.runtime/phase-3/frontend-supply-runtime-gate.json',
                '.runtime/phase-3/frontend-supply/browser-evidence.json',
                '.runtime/phase-3/postgres-runtime-evidence.json',
                '.runtime/phase-3/redis-multi-replica-runtime-evidence.json',
                '.runtime/phase-3/triple-aaa-verify.json',
            }) and (
            not any(part.startswith('.env') or part in {'node_modules', '__pycache__'}
                    or part.endswith(('.pem', '.key')) for part in p.parts))


def snapshot(root: Path, inventory: Path, output: Path) -> None:
    if output.exists():
        raise ValueError('new version directory required; never replace a bundle')
    requirements = json.loads(inventory.read_text())
    paths = set()
    for relative in requirements['missing_local_references_from_current_clean_run']:
        if relative == '.gauntlet/bar.json':  # Generated by the authentic initializer.
            continue
        if not allowed(relative + '/' if (root / relative).is_dir() else relative):
            raise ValueError(f'non-allowlisted input: {relative}')
        source = root / relative
        if not source.exists() or source.is_symlink():
            raise ValueError(f'missing/unsafe input: {relative}')
        paths.update(p.relative_to(root).as_posix() for p in source.rglob('*') if p.is_file()) if source.is_dir() else paths.add(relative)
    for folder in ('.agent/legacy-v1', '.review-control-history'):
        paths.update(p.relative_to(root).as_posix() for p in (root / folder).rglob('*') if p.is_file())
    paths.update(('.gauntlet-state-of-art/bar.json', '.gauntlet-state-of-art/bar.canonical.json',
                  '.gauntlet-state-of-art/goal.txt'))
    members = [(path, path, path) for path in sorted(paths)]
    for folder, names in {
        '.agent': ('state.json', 'backlog.json', 'execution-log.jsonl', 'verification.jsonl'),
        '.gauntlet': ('state.json', 'bar.json', 'history.jsonl', 'artifacts.jsonl', 'progress.md', 'state.md'),
    }.items():
        members.extend((f'snapshot/{folder}/{name}', f'{folder}/{name}', None) for name in names)
    output.mkdir(parents=True)
    entries = []
    with tarfile.open(output / 'inputs.tar.xz', 'w:xz', preset=6) as archive:
        for member, source, target in members:
            if target and not allowed(target):
                raise ValueError(f'unsafe input: {target}')
            path = root / source
            if any((root / Path(*path.relative_to(root).parts[:i])).is_symlink()
                   for i in range(1, len(path.relative_to(root).parts) + 1)):
                raise ValueError(f'symlink input: {source}')
            data = path.read_bytes()
            info = tarfile.TarInfo(member)
            info.size, info.mode, info.mtime = len(data), 0o644, 0
            archive.addfile(info, io.BytesIO(data))
            entries.append(dict(member=member, source=source, target=target,
                                size=len(data), sha256=hashlib.sha256(data).hexdigest()))
    state = json.loads((root / '.agent/state.json').read_text())
    run = json.loads((root / '.gauntlet/state.json').read_text())
    manifest = dict(schema_version=1, version=output.name,
                    purpose='Authentic historical inputs; no current approval imported',
                    archive_sha256=hashlib.sha256((output / 'inputs.tar.xz').read_bytes()).hexdigest(),
                    inventory_sha256=hashlib.sha256(inventory.read_bytes()).hexdigest(),
                    predecessor=dict(agent_revision=state['state_revision'], status=state['status'],
                                     verification_state=state['verification_state'], run_id=run['run_id'],
                                     repository=run['repository'], goal=run['goal'], bar=run['bar']),
                    files=entries)
    (output / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    parser.add_argument('--inventory', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    snapshot(args.root.resolve(), args.inventory, args.output)
