"""Canonical identity protocols (ports). Implementations must not own RBAC policy."""

from __future__ import annotations

from typing import Protocol


class CredentialVerifier(Protocol):
    def verify(self, user_record: dict, password: str) -> bool: ...


class UserStore(Protocol):
    def get_by_email(self, email: str) -> dict | None: ...
    def get_by_id(self, user_id: str) -> dict | None: ...
    def save(self, record: dict) -> None: ...


class SessionStore(Protocol):
    def create(self, record: dict) -> str: ...
    def get(self, token: str) -> dict | None: ...
    def delete(self, token: str) -> None: ...
    def tokens_for_user(self, user_id: str) -> list[str]: ...


class IdentityProvider(Protocol):
    def login(self, *, email: str, password: str, tenant_id: str, ip: str | None, user_agent: str | None) -> dict: ...
    def validate_session(self, token: str | None) -> dict: ...
    def logout(self, token: str | None) -> None: ...
    def list_sessions(self, user_id: str) -> list[dict]: ...
    def revoke_session(self, token: str) -> int: ...
    def revoke_user_sessions(self, user_id: str, *, reason: str = "manual_revoke") -> int: ...
    def get_user(self, user_id: str) -> dict | None: ...
