"""Validated Redis runtime configuration and production composition helpers.

This module owns the volatile Redis boundary without importing ``redis`` at
module import time.  The production factory is the only path that constructs
the vendor client; it uses a blocking, bounded connection pool and explicit
TLS/authentication settings.  Callers must still perform the asynchronous
readiness check before serving traffic.
"""

from __future__ import annotations

import asyncio
from collections.abc import Mapping
from dataclasses import dataclass, field
import hashlib
import math
import os
from pathlib import Path
import random
import re
import ssl
import threading
import time
from typing import Callable, Literal
from urllib.parse import urlsplit


_ENVIRONMENTS = frozenset(
    {
        "production",
        "prod",
        "live",
        "staging",
        "test",
        "testing",
        "development",
        "dev",
        "local",
    }
)
_PRODUCTION_ENVIRONMENTS = frozenset({"production", "prod", "live", "staging"})
_IDENTIFIER = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$")
_PREFIX = re.compile(r"^[A-Za-z][A-Za-z0-9_.-]{0,31}$")
_KEY_KIND = re.compile(r"^[a-z][a-z0-9_-]{0,31}$")
_PATH_MAX = 4_096
_MANAGED_CLIENT_MARKER = "_rick_locking_managed_client"
_PRODUCTION_CAPABILITY_TOKEN = object()

MAX_REDIS_CONNECTIONS = 256
MAX_REDIS_POOL_TIMEOUT_SECONDS = 30.0
MAX_REDIS_OPERATION_TIMEOUT_SECONDS = 30.0
MAX_REDIS_RETRY_ATTEMPTS = 5
MAX_REDIS_RETRY_DELAY_SECONDS = 5.0
MAX_REDIS_CIRCUIT_COOLDOWN_SECONDS = 86_400.0
MAX_REDIS_HEALTH_INTERVAL_SECONDS = 3_600


class RedisConfigurationError(ValueError):
    """Safe fail-closed configuration error with no value disclosure."""

    code = "invalid_configuration"

    def __init__(self) -> None:
        super().__init__("Invalid Redis configuration.")


class RedisDependencyError(RedisConfigurationError):
    """Raised when the explicitly selected Redis production extra is absent."""

    code = "dependency_unavailable"

    def __init__(self) -> None:
        ValueError.__init__(self, "Redis client dependency is unavailable.")


class RedisNamespaceError(RedisConfigurationError):
    """Raised when a scope cannot produce a safe Redis key namespace."""


class RedisUnavailableError(RuntimeError):
    """Raised when a required Redis capability cannot pass readiness."""

    def __init__(self) -> None:
        super().__init__("Required Redis capability is unavailable.")


def _safe_identifier(value: object, *, allow_none: bool = False) -> str | None:
    if value is None and allow_none:
        return None
    if not isinstance(value, str) or _IDENTIFIER.fullmatch(value) is None:
        raise RedisNamespaceError()
    return value


def _safe_path(value: object, *, required: bool) -> str | None:
    if value is None:
        if required:
            raise RedisConfigurationError()
        return None
    if (
        not isinstance(value, str)
        or not 1 <= len(value) <= _PATH_MAX
        or "\x00" in value
        or any(ord(char) < 0x20 or ord(char) == 0x7F for char in value)
    ):
        raise RedisConfigurationError()
    path = Path(value)
    if required and (not path.is_file() or path.is_symlink()):
        raise RedisConfigurationError()
    return value


@dataclass(frozen=True, slots=True)
class RedisNamespace:
    """A tenant/workspace/collection-bound, cluster-safe key namespace.

    Scope values are hashed before entering a key.  Every key generated by a
    namespace shares one Redis Cluster hash tag, so multi-key Lua scripts stay
    atomic on a clustered deployment.  A global scope is available only by an
    explicit constructor, which prevents an omitted tenant from silently
    becoming a tenant-shared key space.
    """

    tenant_id: str | None
    workspace_id: str | None = None
    collection_id: str | None = None
    prefix: str = "rick"
    environment: str = "production"
    scope: Literal["tenant", "global"] = "tenant"

    def __post_init__(self) -> None:
        environment = (
            self.environment.strip().lower()
            if isinstance(self.environment, str)
            else ""
        )
        if environment not in _ENVIRONMENTS:
            raise RedisNamespaceError()
        if not isinstance(self.prefix, str) or _PREFIX.fullmatch(self.prefix) is None:
            raise RedisNamespaceError()
        if self.scope not in {"tenant", "global"}:
            raise RedisNamespaceError()
        tenant = _safe_identifier(self.tenant_id, allow_none=True)
        workspace = _safe_identifier(self.workspace_id, allow_none=True)
        collection = _safe_identifier(self.collection_id, allow_none=True)
        if self.scope == "tenant" and tenant is None:
            raise RedisNamespaceError()
        if self.scope == "global" and (
            tenant is not None or workspace is not None or collection is not None
        ):
            raise RedisNamespaceError()
        if collection is not None and workspace is None:
            raise RedisNamespaceError()
        object.__setattr__(self, "environment", environment)
        object.__setattr__(self, "tenant_id", tenant)
        object.__setattr__(self, "workspace_id", workspace)
        object.__setattr__(self, "collection_id", collection)

    @classmethod
    def for_tenant(
        cls,
        tenant_id: str,
        *,
        workspace_id: str | None = None,
        collection_id: str | None = None,
        prefix: str = "rick",
        environment: str = "production",
    ) -> "RedisNamespace":
        return cls(
            tenant_id,
            workspace_id,
            collection_id,
            prefix,
            environment,
            "tenant",
        )

    @classmethod
    def global_scope(
        cls,
        *,
        prefix: str = "rick",
        environment: str = "production",
    ) -> "RedisNamespace":
        return cls(None, prefix=prefix, environment=environment, scope="global")

    @property
    def scope_fingerprint(self) -> str:
        material = "\x1f".join(
            (
                self.environment,
                self.scope,
                self.tenant_id or "",
                self.workspace_id or "",
                self.collection_id or "",
            )
        )
        return hashlib.sha256(material.encode("utf-8")).hexdigest()[:32]

    def key(self, kind: str, logical_key: str) -> str:
        """Return a bounded key without exposing scope or logical-key text."""

        if not isinstance(kind, str) or _KEY_KIND.fullmatch(kind) is None:
            raise RedisNamespaceError()
        if (
            not isinstance(logical_key, str)
            or not 1 <= len(logical_key) <= 512
            or any(ord(char) < 0x20 or ord(char) == 0x7F for char in logical_key)
        ):
            raise RedisNamespaceError()
        tag = f"{self.prefix}:v1:{self.environment}:s:{self.scope_fingerprint}"
        logical_fingerprint = hashlib.sha256(
            logical_key.encode("utf-8")
        ).hexdigest()[:32]
        return f"{{{tag}}}:{kind}:k:{logical_fingerprint}"

    def __repr__(self) -> str:
        return (
            "RedisNamespace("
            f"scope={self.scope!r}, prefix={self.prefix!r}, "
            f"environment={self.environment!r}, "
            f"scope_fingerprint={self.scope_fingerprint!r})"
        )


@dataclass(frozen=True, slots=True)
class RedisRetryPolicy:
    """Finite exponential backoff policy with a hard delay ceiling."""

    max_attempts: int = 3
    base_delay_seconds: float = 0.05
    max_delay_seconds: float = 0.25
    jitter_ratio: float = 0.0

    def __post_init__(self) -> None:
        if (
            type(self.max_attempts) is not int
            or not 1 <= self.max_attempts <= MAX_REDIS_RETRY_ATTEMPTS
        ):
            raise RedisConfigurationError()
        for value in (
            self.base_delay_seconds,
            self.max_delay_seconds,
            self.jitter_ratio,
        ):
            if (
                isinstance(value, bool)
                or not isinstance(value, (int, float))
                or not math.isfinite(float(value))
            ):
                raise RedisConfigurationError()
        if not 0.0 <= float(self.base_delay_seconds) <= MAX_REDIS_RETRY_DELAY_SECONDS:
            raise RedisConfigurationError()
        if not (
            float(self.base_delay_seconds)
            <= float(self.max_delay_seconds)
            <= MAX_REDIS_RETRY_DELAY_SECONDS
        ):
            raise RedisConfigurationError()
        if not 0.0 <= float(self.jitter_ratio) <= 1.0:
            raise RedisConfigurationError()

    @classmethod
    def single_attempt(cls) -> "RedisRetryPolicy":
        return cls(max_attempts=1, base_delay_seconds=0.0, max_delay_seconds=0.0)

    def delay_seconds(self, retry_number: int) -> float:
        if type(retry_number) is not int or not 1 <= retry_number < self.max_attempts:
            raise RedisConfigurationError()
        delay = min(
            float(self.max_delay_seconds),
            float(self.base_delay_seconds) * (2 ** (retry_number - 1)),
        )
        if self.jitter_ratio:
            delay = min(
                float(self.max_delay_seconds),
                delay * (1.0 + random.random() * float(self.jitter_ratio)),
            )
        return delay


class RedisCircuitState(str):
    """String-compatible circuit state values for diagnostics."""

    CLOSED = "closed"
    OPEN = "open"
    HALF_OPEN = "half_open"


class RedisCircuitBreaker:
    """Thread-safe closed/open/half-open circuit with one recovery probe."""

    def __init__(
        self,
        *,
        failure_threshold: int = 3,
        cooldown_seconds: float = 10.0,
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        if type(failure_threshold) is not int or not 1 <= failure_threshold <= 32:
            raise RedisConfigurationError()
        if (
            isinstance(cooldown_seconds, bool)
            or not isinstance(cooldown_seconds, (int, float))
            or not 0.1 <= float(cooldown_seconds) <= MAX_REDIS_CIRCUIT_COOLDOWN_SECONDS
            or not math.isfinite(float(cooldown_seconds))
        ):
            raise RedisConfigurationError()
        if not callable(clock):
            raise RedisConfigurationError()
        self.failure_threshold = failure_threshold
        self.cooldown_seconds = float(cooldown_seconds)
        self._clock = clock
        self._lock = threading.RLock()
        self._state = RedisCircuitState.CLOSED
        self._failures = 0
        self._opened_until = 0.0
        self._probe_in_flight = False
        self._generation = 0

    def _now(self) -> float:
        try:
            value = float(self._clock())
        except Exception:
            raise RedisConfigurationError() from None
        if not math.isfinite(value):
            raise RedisConfigurationError()
        return value

    @property
    def state(self) -> str:
        with self._lock:
            if self._state == RedisCircuitState.OPEN and self._now() >= self._opened_until:
                return RedisCircuitState.HALF_OPEN
            return self._state

    @property
    def failure_count(self) -> int:
        with self._lock:
            return self._failures

    @property
    def is_open(self) -> bool:
        return self.state == RedisCircuitState.OPEN

    def begin_call(self) -> int | None:
        """Reserve a call and return its circuit generation, or reject it."""

        now = self._now()
        with self._lock:
            if self._state == RedisCircuitState.OPEN:
                if now < self._opened_until or self._probe_in_flight:
                    return None
                self._state = RedisCircuitState.HALF_OPEN
                self._probe_in_flight = True
                return self._generation
            if self._state == RedisCircuitState.HALF_OPEN:
                if self._probe_in_flight:
                    return None
                self._probe_in_flight = True
                return self._generation
            return self._generation

    def before_call(self) -> bool:
        """Compatibility gate returning only whether a call may start."""

        return self.begin_call() is not None

    def record_success(self, generation: int | None = None) -> None:
        with self._lock:
            if generation is not None and generation != self._generation:
                return
            self._state = RedisCircuitState.CLOSED
            self._failures = 0
            self._opened_until = 0.0
            self._probe_in_flight = False
            self._generation += 1

    def record_failure(self, generation: int | None = None) -> None:
        now = self._now()
        with self._lock:
            if generation is not None and generation != self._generation:
                return
            if self._state == RedisCircuitState.HALF_OPEN:
                self._state = RedisCircuitState.OPEN
                self._opened_until = now + self.cooldown_seconds
                self._probe_in_flight = False
                self._generation += 1
                return
            self._failures += 1
            self._probe_in_flight = False
            if self._failures >= self.failure_threshold:
                self._state = RedisCircuitState.OPEN
                self._opened_until = now + self.cooldown_seconds
                self._generation += 1

    def release_call(self, generation: int) -> None:
        """Release an unfinished half-open probe without recording success."""

        if type(generation) is not int:
            return
        with self._lock:
            if generation == self._generation and self._state == RedisCircuitState.HALF_OPEN:
                self._probe_in_flight = False


@dataclass(frozen=True, slots=True, init=False)
class RedisSettings:
    """All Redis connection and resilience settings with hard upper bounds."""

    url: str
    environment: str
    namespace_prefix: str
    username: str | None
    password: str | None = field(repr=False)
    require_tls: bool | None
    require_auth: bool | None
    verify_tls: bool
    tls_ca_file: str | None
    tls_cert_file: str | None
    tls_key_file: str | None
    max_connections: int
    pool_timeout: float
    socket_connect_timeout: float
    socket_timeout: float
    operation_timeout: float
    retry_max_attempts: int
    retry_base_delay_seconds: float
    retry_max_delay_seconds: float
    retry_jitter_ratio: float
    circuit_failure_threshold: int
    circuit_cooldown_seconds: float
    health_check_interval: int

    def __init__(
        self,
        *,
        url: str,
        environment: str = "production",
        namespace_prefix: str = "rick",
        username: str | None = None,
        password: str | None = None,
        require_tls: bool | None = None,
        require_auth: bool | None = None,
        verify_tls: bool = True,
        tls_ca_file: str | None = None,
        tls_cert_file: str | None = None,
        tls_key_file: str | None = None,
        max_connections: int = 32,
        pool_timeout: float = 1.0,
        socket_connect_timeout: float = 1.0,
        socket_timeout: float = 1.0,
        operation_timeout: float = 2.0,
        retry_max_attempts: int = 3,
        retry_base_delay_seconds: float = 0.05,
        retry_max_delay_seconds: float = 0.25,
        retry_jitter_ratio: float = 0.0,
        circuit_failure_threshold: int = 3,
        circuit_cooldown_seconds: float = 10.0,
        health_check_interval: int = 30,
    ) -> None:
        object.__setattr__(self, "url", url.strip() if isinstance(url, str) else url)
        object.__setattr__(
            self,
            "environment",
            environment.strip().lower()
            if isinstance(environment, str)
            else environment,
        )
        object.__setattr__(self, "namespace_prefix", namespace_prefix)
        object.__setattr__(
            self,
            "username",
            username.strip() if isinstance(username, str) else username,
        )
        object.__setattr__(self, "password", password if isinstance(password, str) else password)
        object.__setattr__(self, "require_tls", require_tls)
        object.__setattr__(self, "require_auth", require_auth)
        object.__setattr__(self, "verify_tls", verify_tls)
        object.__setattr__(self, "tls_ca_file", tls_ca_file)
        object.__setattr__(self, "tls_cert_file", tls_cert_file)
        object.__setattr__(self, "tls_key_file", tls_key_file)
        object.__setattr__(self, "max_connections", max_connections)
        object.__setattr__(self, "pool_timeout", pool_timeout)
        object.__setattr__(self, "socket_connect_timeout", socket_connect_timeout)
        object.__setattr__(self, "socket_timeout", socket_timeout)
        object.__setattr__(self, "operation_timeout", operation_timeout)
        object.__setattr__(self, "retry_max_attempts", retry_max_attempts)
        object.__setattr__(self, "retry_base_delay_seconds", retry_base_delay_seconds)
        object.__setattr__(self, "retry_max_delay_seconds", retry_max_delay_seconds)
        object.__setattr__(self, "retry_jitter_ratio", retry_jitter_ratio)
        object.__setattr__(self, "circuit_failure_threshold", circuit_failure_threshold)
        object.__setattr__(self, "circuit_cooldown_seconds", circuit_cooldown_seconds)
        object.__setattr__(self, "health_check_interval", health_check_interval)
        self.validate()

    @property
    def is_production(self) -> bool:
        return self.environment in _PRODUCTION_ENVIRONMENTS

    @property
    def tls_enabled(self) -> bool:
        return urlsplit(self.url).scheme == "rediss"

    @property
    def effective_require_tls(self) -> bool:
        return self.is_production if self.require_tls is None else self.require_tls

    @property
    def effective_require_auth(self) -> bool:
        return self.is_production if self.require_auth is None else self.require_auth

    @property
    def retry_policy(self) -> RedisRetryPolicy:
        return RedisRetryPolicy(
            max_attempts=self.retry_max_attempts,
            base_delay_seconds=self.retry_base_delay_seconds,
            max_delay_seconds=self.retry_max_delay_seconds,
            jitter_ratio=self.retry_jitter_ratio,
        )

    def circuit_breaker(
        self, *, clock: Callable[[], float] = time.monotonic
    ) -> RedisCircuitBreaker:
        return RedisCircuitBreaker(
            failure_threshold=self.circuit_failure_threshold,
            cooldown_seconds=self.circuit_cooldown_seconds,
            clock=clock,
        )

    def namespace_for(
        self,
        tenant_id: str,
        *,
        workspace_id: str | None = None,
        collection_id: str | None = None,
    ) -> RedisNamespace:
        return RedisNamespace.for_tenant(
            tenant_id,
            workspace_id=workspace_id,
            collection_id=collection_id,
            prefix=self.namespace_prefix,
            environment=self.environment,
        )

    def validate(self) -> None:
        if self.environment not in _ENVIRONMENTS:
            raise RedisConfigurationError()
        if not isinstance(self.url, str) or not 1 <= len(self.url) <= 2_048:
            raise RedisConfigurationError()
        try:
            parsed = urlsplit(self.url)
            if (
                any(ord(char) < 0x20 or ord(char) == 0x7F for char in self.url)
                or parsed.scheme not in {"redis", "rediss"}
                or not parsed.hostname
            ):
                raise RedisConfigurationError()
            if parsed.username is not None and not parsed.username:
                raise RedisConfigurationError()
            if parsed.password is not None and not parsed.password:
                raise RedisConfigurationError()
            if parsed.query or parsed.fragment:
                raise RedisConfigurationError()
            if parsed.port is not None and not 1 <= parsed.port <= 65_535:
                raise RedisConfigurationError()
        except (ValueError, RedisConfigurationError):
            raise RedisConfigurationError() from None
        if parsed.path not in {"", "/"}:
            if not re.fullmatch(r"/[0-9]{1,3}", parsed.path):
                raise RedisConfigurationError()
            if not 0 <= int(parsed.path[1:]) <= 255:
                raise RedisConfigurationError()
        if (
            not isinstance(self.namespace_prefix, str)
            or _PREFIX.fullmatch(self.namespace_prefix) is None
        ):
            raise RedisConfigurationError()
        if self.username is not None and (
            not isinstance(self.username, str)
            or not 1 <= len(self.username) <= 256
            or any(ord(char) < 0x20 or ord(char) == 0x7F for char in self.username)
        ):
            raise RedisConfigurationError()
        if self.password is not None and (
            not isinstance(self.password, str)
            or not 1 <= len(self.password) <= 512
            or "\x00" in self.password
        ):
            raise RedisConfigurationError()
        if self.require_tls is not None and type(self.require_tls) is not bool:
            raise RedisConfigurationError()
        if self.require_auth is not None and type(self.require_auth) is not bool:
            raise RedisConfigurationError()
        if type(self.verify_tls) is not bool:
            raise RedisConfigurationError()
        if self.is_production and (
            self.require_tls is False or parsed.scheme != "rediss"
        ):
            raise RedisConfigurationError()
        if self.effective_require_tls and parsed.scheme != "rediss":
            raise RedisConfigurationError()
        if self.is_production and not self.verify_tls:
            raise RedisConfigurationError()
        has_url_password = parsed.password is not None
        if self.is_production and self.require_auth is False:
            raise RedisConfigurationError()
        if self.effective_require_auth and not (has_url_password or self.password):
            raise RedisConfigurationError()
        if self.tls_cert_file is None and self.tls_key_file is not None:
            raise RedisConfigurationError()
        if self.tls_key_file is None and self.tls_cert_file is not None:
            raise RedisConfigurationError()
        _safe_path(self.tls_ca_file, required=self.is_production and self.tls_ca_file is not None)
        _safe_path(
            self.tls_cert_file,
            required=self.is_production and self.tls_cert_file is not None,
        )
        _safe_path(self.tls_key_file, required=self.is_production and self.tls_key_file is not None)
        if (
            type(self.max_connections) is not int
            or not 1 <= self.max_connections <= MAX_REDIS_CONNECTIONS
        ):
            raise RedisConfigurationError()
        for value, maximum in (
            (self.pool_timeout, MAX_REDIS_POOL_TIMEOUT_SECONDS),
            (self.socket_connect_timeout, MAX_REDIS_OPERATION_TIMEOUT_SECONDS),
            (self.socket_timeout, MAX_REDIS_OPERATION_TIMEOUT_SECONDS),
            (self.operation_timeout, MAX_REDIS_OPERATION_TIMEOUT_SECONDS),
        ):
            if (
                isinstance(value, bool)
                or not isinstance(value, (int, float))
                or not math.isfinite(float(value))
                or not 0.0 < float(value) <= maximum
            ):
                raise RedisConfigurationError()
        if (
            self.pool_timeout > self.operation_timeout
            or self.socket_connect_timeout > self.operation_timeout
            or self.socket_timeout > self.operation_timeout
        ):
            raise RedisConfigurationError()
        RedisRetryPolicy(
            max_attempts=self.retry_max_attempts,
            base_delay_seconds=self.retry_base_delay_seconds,
            max_delay_seconds=self.retry_max_delay_seconds,
            jitter_ratio=self.retry_jitter_ratio,
        )
        if (
            type(self.circuit_failure_threshold) is not int
            or not 1 <= self.circuit_failure_threshold <= 32
        ):
            raise RedisConfigurationError()
        if (
            isinstance(self.circuit_cooldown_seconds, bool)
            or not isinstance(self.circuit_cooldown_seconds, (int, float))
            or not math.isfinite(float(self.circuit_cooldown_seconds))
            or not 0.1 <= float(self.circuit_cooldown_seconds) <= MAX_REDIS_CIRCUIT_COOLDOWN_SECONDS
        ):
            raise RedisConfigurationError()
        if (
            type(self.health_check_interval) is not int
            or not 0 <= self.health_check_interval <= MAX_REDIS_HEALTH_INTERVAL_SECONDS
        ):
            raise RedisConfigurationError()

    @classmethod
    def from_env(cls, environ: Mapping[str, str] | None = None) -> "RedisSettings":
        values = os.environ if environ is None else environ

        def text(name: str, *aliases: str) -> str | None:
            for candidate in (name, *aliases):
                value = values.get(candidate)
                if value is not None:
                    return value
            return None

        def integer(name: str, default: int) -> int:
            value = text(name)
            if value is None or not isinstance(value, str):
                return default
            try:
                return int(value.strip())
            except (TypeError, ValueError):
                raise RedisConfigurationError() from None

        def number(name: str, default: float) -> float:
            value = text(name)
            if value is None or not isinstance(value, str):
                return default
            try:
                return float(value.strip())
            except (TypeError, ValueError):
                raise RedisConfigurationError() from None

        def boolean(name: str, default: bool | None) -> bool | None:
            value = text(name)
            if value is None:
                return default
            normalized = value.strip().lower()
            if normalized in {"1", "true", "yes", "on"}:
                return True
            if normalized in {"0", "false", "no", "off"}:
                return False
            raise RedisConfigurationError()

        environment = text("RICK_ENV", "ENVIRONMENT") or "production"
        return cls(
            url=text("RICK_REDIS_URL", "REDIS_URL") or "",
            environment=environment,
            namespace_prefix=text("RICK_REDIS_NAMESPACE") or "rick",
            username=text("RICK_REDIS_USERNAME", "REDIS_USERNAME"),
            password=text("RICK_REDIS_PASSWORD", "REDIS_PASSWORD"),
            require_tls=boolean("RICK_REDIS_REQUIRE_TLS", None),
            require_auth=boolean("RICK_REDIS_REQUIRE_AUTH", None),
            verify_tls=bool(boolean("RICK_REDIS_VERIFY_TLS", True)),
            tls_ca_file=text("RICK_REDIS_TLS_CA_FILE"),
            tls_cert_file=text("RICK_REDIS_TLS_CERT_FILE"),
            tls_key_file=text("RICK_REDIS_TLS_KEY_FILE"),
            max_connections=integer("RICK_REDIS_MAX_CONNECTIONS", 32),
            pool_timeout=number("RICK_REDIS_POOL_TIMEOUT_SECONDS", 1.0),
            socket_connect_timeout=number("RICK_REDIS_CONNECT_TIMEOUT_SECONDS", 1.0),
            socket_timeout=number("RICK_REDIS_SOCKET_TIMEOUT_SECONDS", 1.0),
            operation_timeout=number("RICK_REDIS_OPERATION_TIMEOUT_SECONDS", 2.0),
            retry_max_attempts=integer("RICK_REDIS_RETRY_ATTEMPTS", 3),
            retry_base_delay_seconds=number("RICK_REDIS_RETRY_BASE_SECONDS", 0.05),
            retry_max_delay_seconds=number("RICK_REDIS_RETRY_MAX_SECONDS", 0.25),
            retry_jitter_ratio=number("RICK_REDIS_RETRY_JITTER", 0.0),
            circuit_failure_threshold=integer("RICK_REDIS_CIRCUIT_FAILURE_THRESHOLD", 3),
            circuit_cooldown_seconds=number("RICK_REDIS_CIRCUIT_COOLDOWN_SECONDS", 10.0),
            health_check_interval=integer("RICK_REDIS_HEALTH_CHECK_INTERVAL_SECONDS", 30),
        )

    def _connection_options(self) -> dict[str, object]:
        """Build vendor options without exposing them through public errors."""

        options: dict[str, object] = {
            "max_connections": self.max_connections,
            "timeout": self.pool_timeout,
            "socket_connect_timeout": self.socket_connect_timeout,
            "socket_timeout": self.socket_timeout,
            "socket_keepalive": True,
            "health_check_interval": self.health_check_interval,
            # Operation retries live in this package so their budget and
            # circuit state are visible.  Avoid a second vendor retry layer.
            "retry_on_timeout": False,
        }
        if self.username is not None:
            options["username"] = self.username
        if self.password is not None:
            options["password"] = self.password
        if self.tls_enabled:
            options["ssl_cert_reqs"] = (
                ssl.CERT_REQUIRED if self.verify_tls else ssl.CERT_NONE
            )
            options["ssl_check_hostname"] = self.verify_tls
            if self.tls_ca_file is not None:
                options["ssl_ca_certs"] = self.tls_ca_file
            if self.tls_cert_file is not None:
                options["ssl_certfile"] = self.tls_cert_file
                options["ssl_keyfile"] = self.tls_key_file
        return options

    def __repr__(self) -> str:
        return (
            "RedisSettings("
            f"environment={self.environment!r}, tls={self.tls_enabled!r}, "
            f"auth_required={self.effective_require_auth!r}, "
            f"max_connections={self.max_connections!r}, "
            f"operation_timeout={self.operation_timeout!r}, "
            f"retry_max_attempts={self.retry_max_attempts!r})"
        )


RedisConfig = RedisSettings


def create_redis_client(settings: RedisSettings):
    """Construct the real async Redis client with a bounded pool.

    No socket is opened here.  A caller must run :func:`require_redis_ready`
    before treating the capability as available.
    """

    if not isinstance(settings, RedisSettings):
        raise RedisConfigurationError()
    settings.validate()
    try:
        import redis.asyncio as redis_asyncio
    except ImportError:
        raise RedisDependencyError() from None
    try:
        pool_type = getattr(redis_asyncio, "BlockingConnectionPool")
        redis_type = getattr(redis_asyncio, "Redis")
        pool_factory = getattr(pool_type, "from_url")
        pool = pool_factory(settings.url, **settings._connection_options())
        client = redis_type(connection_pool=pool, decode_responses=True)
        try:
            # A local/test client must not be reusable through a production
            # factory, even when both clients use the same vendor type.
            setattr(client, _MANAGED_CLIENT_MARKER, settings.is_production)
        except Exception:
            raise RedisConfigurationError() from None
        return client
    except RedisConfigurationError:
        raise
    except Exception:
        # Vendor construction errors may contain the URL or credentials.
        raise RedisConfigurationError() from None


def validate_production_capability(capability: object) -> object:
    """Reject local/malformed capabilities before production startup."""

    if (
        capability is None
        or getattr(capability, "backend_kind", None) != "redis"
        or getattr(capability, "production_safe", False) is not True
        or not callable(getattr(capability, "health_check", None))
        or not callable(getattr(capability, "readiness_check", None))
    ):
        raise RedisConfigurationError()
    return capability


async def require_redis_ready(capability: object) -> object:
    """Perform the required live readiness check and fail closed on failure."""

    validate_production_capability(capability)
    try:
        result = capability.readiness_check()  # type: ignore[attr-defined]
        if hasattr(result, "__await__"):
            result = await result
    except BaseException as error:
        if isinstance(error, KeyboardInterrupt | SystemExit | asyncio.CancelledError):
            raise
        raise RedisUnavailableError() from None
    if result is not True:
        raise RedisUnavailableError()
    return capability


def create_redis_lease_store(
    settings: RedisSettings,
    namespace: RedisNamespace,
    *,
    client: object | None = None,
):
    """Compose a production Redis lease store from validated settings."""

    if not isinstance(settings, RedisSettings) or not isinstance(namespace, RedisNamespace):
        raise RedisConfigurationError()
    settings.validate()
    if namespace.environment != settings.environment:
        raise RedisConfigurationError()
    if settings.is_production and client is not None and getattr(
        client, _MANAGED_CLIENT_MARKER, False
    ) is not True:
        # A shared production pool is allowed only when it came from this
        # package's validated vendor factory; arbitrary doubles would defeat
        # the startup gate.
        raise RedisConfigurationError()
    actual_client = create_redis_client(settings) if client is None else client
    try:
        from rick_locking.redis import RedisLeaseStore

        store = RedisLeaseStore(
            actual_client,
            timeout=settings.operation_timeout,
            close_client=client is None,
            namespace=namespace,
            retry_policy=settings.retry_policy,
            circuit_breaker=settings.circuit_breaker(),
        )
        if settings.is_production:
            store._mark_production_safe(_PRODUCTION_CAPABILITY_TOKEN)
        return store
    except RedisConfigurationError:
        raise
    except Exception:
        raise RedisConfigurationError() from None


def create_redis_lease_client(
    settings: RedisSettings,
    namespace: RedisNamespace,
    *,
    client: object | None = None,
    owner_factory: Callable[[], str] | None = None,
    cleanup_timeout: float = 2.0,
):
    """Compose the owner-generating production Redis lease client."""

    from rick_locking.redis import RedisLeaseClient

    store = create_redis_lease_store(settings, namespace, client=client)
    return RedisLeaseClient(
        store=store,
        owner_factory=owner_factory,
        cleanup_timeout=cleanup_timeout,
    )


def create_redis_rate_limiter(
    settings: RedisSettings,
    namespace: RedisNamespace,
    *,
    client: object | None = None,
):
    """Compose the production distributed rate limiter."""

    from rick_locking.rate_limit import RedisRateLimiter

    if not isinstance(settings, RedisSettings) or not isinstance(namespace, RedisNamespace):
        raise RedisConfigurationError()
    settings.validate()
    if namespace.environment != settings.environment:
        raise RedisConfigurationError()
    if settings.is_production and client is not None and getattr(
        client, _MANAGED_CLIENT_MARKER, False
    ) is not True:
        raise RedisConfigurationError()
    actual_client = create_redis_client(settings) if client is None else client
    try:
        limiter = RedisRateLimiter(
            actual_client,
            namespace=namespace,
            timeout=settings.operation_timeout,
            close_client=client is None,
            retry_policy=settings.retry_policy,
            circuit_breaker=settings.circuit_breaker(),
        )
        if settings.is_production:
            limiter._mark_production_safe(_PRODUCTION_CAPABILITY_TOKEN)
        return limiter
    except RedisConfigurationError:
        raise
    except Exception:
        raise RedisConfigurationError() from None


__all__ = [
    "MAX_REDIS_CONNECTIONS",
    "MAX_REDIS_CIRCUIT_COOLDOWN_SECONDS",
    "MAX_REDIS_HEALTH_INTERVAL_SECONDS",
    "MAX_REDIS_OPERATION_TIMEOUT_SECONDS",
    "MAX_REDIS_POOL_TIMEOUT_SECONDS",
    "MAX_REDIS_RETRY_ATTEMPTS",
    "MAX_REDIS_RETRY_DELAY_SECONDS",
    "RedisCircuitBreaker",
    "RedisCircuitState",
    "RedisConfig",
    "RedisConfigurationError",
    "RedisDependencyError",
    "RedisNamespace",
    "RedisNamespaceError",
    "RedisRetryPolicy",
    "RedisSettings",
    "RedisUnavailableError",
    "create_redis_client",
    "create_redis_lease_client",
    "create_redis_lease_store",
    "create_redis_rate_limiter",
    "require_redis_ready",
    "validate_production_capability",
]
